# Generated by Django 5.2.6 on 2025-09-15 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planetarium', '0002_presenter_ticket_unique_seat_per_session_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='presenter',
            options={'ordering': ['last_name', 'first_name']},
        ),
    ]
