# Generated by Django 5.2.6 on 2025-09-16 20:54

import planetarium.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planetarium', '0003_alter_presenter_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='astronomyshow',
            name='poster',
            field=models.ImageField(blank=True, null=True, upload_to=planetarium.models.show_poster_file_path),
        ),
    ]
